apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso
spec:
  channel: stable
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace