apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-registry-operator
spec:
  channel: 2.x
  name: service-registry-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace