kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: chartmuseum
  namespace: chartmuseum
spec:
  host: chartmuseum.<YOUR_HOST_DOMAIN>
  to:
    kind: Service
    name: chartmuseum
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None